name: test
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: EEA
        run: mvn --batch-mode --update-snapshots verify
